name: Auto Label Issues

on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Label issues
        uses: actions/github-script@v6
        with:
          script: |
            const title = context.issue.title.toLowerCase();
            const labels = [];
            if (title.includes('error')) {
              labels.push('bug');
            }
            if (title.includes('add')) {
              labels.push('feature');
            }
            if (labels.length > 0) {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: labels
              });
            }